### ISSUE TITLE
Export Group Information

### ISSUE THREAD

**Issue by KunX** [savoirfairelinux/mod-rawsocket#3]
Do you think it would be hard to export servicegroup and hostgroup membership aswell on the message? It could facilitate building SLA reports on ELK Stack.

**Comment by Seb-Solon** [comment]
If you want to include all members of a service/hostgroup in the log line you will have to remember them in a dict. Member are accessible in initial broks, you just have to implement manage_hosgroup/servicegroup_status_brok. For now it's only pass, you have to store members here and retrieve them later.

Is it clear?

**Comment by KunX** [comment]
Yes, that was pretty clear, I'll try to work something out. Thank you.
