### ISSUE TITLE
Wrong timezone on message

### ISSUE THREAD

**Issue by KunX** [savoirfairelinux/mod-rawsocket#4]
On my shinken instance the timezone information exported by rawsocket is wrong, all daemons are configured to use America/Sao_Paulo (-03:00) but the log information has +3 timezone attached. Is there any configuration I can do on the module to force the timezone?

2015−10−21T10:25:38+03:00

**Comment by Seb-Solon** [comment]
Actually, it was made by desgin to get ISO 8601 format. But I've read it again and it looks like I was kinda tired when I did this code. Because obviously we should put - for negative timezone.

I can't remember why I had to change the sign. For now just fix the function 

```
    @staticmethod
    def get_formatted_tz():
        tz = str.format('{0:05.2f}', float(time.timezone) / 3600 - time.daylight).replace('.', ':')
        return  '-' + tz if time.timezone > 0 else '+' + tz
```
to
```
    @staticmethod
    def get_formatted_tz():
        return str.format('{0:05.2f}', float(time.timezone) / 3600 - time.daylight).replace('.', ':')
```

**Comment by KunX** [comment]
I couldn't find that block of code on the raw-socket module installed by shinken install.
I did found the following code:

```
formatted = datetime.datetime.fromtimestamp(int(t)).strftime('%Y-%m-%dT%H:%M:%S')
                tz = str.format('{0:+06.2f}', float(time.timezone) / 3600).replace('.', ':')
                isodate = formatted + tz
```

**Comment by Seb-Solon** [comment]
I would not recommend to use shinken install. Or use it to install from local source (which could be a tarball of the current master). 

Here the issue is the + in the 0:+06.2f format.

**Comment by KunX** [comment]
I installed the master version and everything is working now. I thought shinken install would always grab the most recent version of the module. Thank you very much for your help.

**Comment by Seb-Solon** [comment]
HUm so the - + thing is correct then. good to head it :)

**Comment by KunX** [comment]
Yes, I was using the shinken install version, that seems to be very buggy. Your version is working without any problems.
